services:
  lightjoy:
    build: .
    container_name: lightjoy
    ports:
      - "8080:8080"
      # Moonlight Streaming UDP Ports
      - "47998:47998/udp"
      - "47999:47999/udp"
      - "48000:48000/udp"
      - "48002:48002/udp"
      - "48010:48010/udp"
    restart: unless-stopped
